title: YouTube Music API Proxy Documentation
description: Comprehensive documentation for the YouTube Music API Proxy
url: "https://bluscream.github.io"
baseurl: "/youtube-music-api-proxy"

# GitHub Pages settings
github:
  repository_url: "https://github.com/Bluscream/youtube-music-api-proxy"
  repository_name: "youtube-music-api-proxy"
  branch: "main"

# Site settings
author:
  name: "Bluscream"
  email: ""
  bio: "YouTube Music API Proxy Developer"
  location: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Bluscream"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      author_profile: false
      share: false
      comments: false

# SEO
seo:
  type: "WebSite"
  name: "YouTube Music API Proxy Documentation"
  description: "Comprehensive documentation for the YouTube Music API Proxy"
  url: "https://bluscream.github.io/youtube-music-api-proxy"

# Head and footer
head_scripts:
  - "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"
  - "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui.css"

footer_scripts:
  - "/assets/js/custom.js"

# Exclude from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.json"
  - "*.xml"
  - "*.txt"
  - "*.log"
  - "*.tmp"
  - "*.temp"
  - "*.cache"
  - "*.bak"
  - "*.swp"
  - "*.swo"
  - "*~"
  - ".#*"
  - "#*#"
  - ".#*#"
  - "Thumbs.db"
  - "ehthumbs.db"
  - "Desktop.ini"
  - "$RECYCLE.BIN/"
  - "*.cab"
  - "*.msi"
  - "*.msm"
  - "*.msp"
  - "*.lnk" 